/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */

package org.opensearch.replication

import org.opensearch.index.engine.DeletionStrategy
import org.opensearch.index.engine.EngineConfig
import org.opensearch.index.engine.IndexingStrategy
import org.opensearch.index.engine.InternalEngine
import org.opensearch.index.seqno.SequenceNumbers

class ReplicationEngine(config: EngineConfig) : InternalEngine(config) {

    override fun assertPrimaryIncomingSequenceNumber(origin: Operation.Origin, seqNo: Long): Boolean {
        assert(origin == Operation.Origin.PRIMARY) { "Expected origin PRIMARY for replicated ops but was $origin" }
        assert(seqNo != SequenceNumbers.UNASSIGNED_SEQ_NO) { "Expected valid sequence number for replicated op but was unassigned" }
        return true
    }

    override fun generateSeqNoForOperationOnPrimary(operation: Operation): Long {
        check(operation.seqNo() != SequenceNumbers.UNASSIGNED_SEQ_NO) { "Expected valid sequence number for replicate op but was unassigned"}
        return operation.seqNo()
    }

    /**
     * Route all index operations through the non-primary planning path. CCR replays operations with
     * PRIMARY origin but they need non-primary planning to avoid version conflict checks and in-flight
     * doc acquisition. We create a copy with REPLICA origin to satisfy the assertions in both the engine
     * and the new OperationStrategyPlanner.
     */
    override fun indexingStrategyForOperation(index: Index): IndexingStrategy {
        val replicaIndex = Index(
            index.uid(), index.parsedDoc(), index.seqNo(), index.primaryTerm(),
            index.version(), null, Operation.Origin.REPLICA,
            index.startTime(), index.getAutoGeneratedIdTimestamp(), index.isRetry,
            SequenceNumbers.UNASSIGNED_SEQ_NO, 0
        )
        return planIndexingAsNonPrimary(replicaIndex)
    }

    // Same as above for delete operations.
    override fun deletionStrategyForOperation(delete: Delete): DeletionStrategy {
        val replicaDelete = Delete(
            delete.id(), delete.uid(), delete.seqNo(), delete.primaryTerm(),
            delete.version(), null, Operation.Origin.REPLICA,
            delete.startTime(), SequenceNumbers.UNASSIGNED_SEQ_NO, 0
        )
        return planDeletionAsNonPrimary(replicaDelete)
    }

    override fun assertNonPrimaryOrigin(operation: Operation): Boolean {
        return true
    }
}
