#
# SPDX-License-Identifier: Apache-2.0
#
# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.
#
# Modifications Copyright OpenSearch Contributors. See
# GitHub history for details.
#

version: '3'
services:
  os-leader1:
    image: opensearch-with-replication
    container_name: os-leader1
    environment:
      - cluster.name=os-leader
      - node.name=os-leader1
      - discovery.seed_hosts=os-leader1
      - cluster.initial_master_nodes=os-leader1
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - plugins.security.unsupported.inject_user.enabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - os-leader-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      os-net:
        ipv4_address: 172.18.0.10
  os-follower1:
    image: opensearch-with-replication
    build:
      context: .
      dockerfile: Dockerfile
    container_name: os-follower1
    environment:
      - cluster.name=os-follower
      - node.name=os-follower1
      - discovery.seed_hosts=os-follower1
      - cluster.initial_master_nodes=os-follower1
      - plugins.security.unsupported.inject_user.enabled=true
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - os-follower-data1:/usr/share/opensearch/data
    ports:
      - 9201:9200
      - 9601:9600 # required for Performance Analyzer
    networks:
      os-net:
        ipv4_address: 172.18.0.20

volumes:
  os-leader-data1:
  os-follower-data1:

networks:
  os-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

