name: PR Code Review

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  Code-Diff-Analyzer:
    uses: opensearch-project/opensearch-build/.github/workflows/code-diff-analyzer.yml@main
    permissions:
      id-token: write
      pull-requests: write
    secrets:
      BEDROCK_ACCESS_ROLE: ${{ secrets.BEDROCK_ACCESS_ROLE }}
    with:
      skip_diff_analyzer_with_label_name: 'skip-diff-analyzer'
      update_pr_comment_with_analyzer_report: true
      hard_fail_level: 2

  Code-Diff-Reviewer:
    uses: opensearch-project/opensearch-build/.github/workflows/code-diff-reviewer.yml@main
    needs: Code-Diff-Analyzer
    permissions:
      id-token: write
      pull-requests: write
    secrets:
      BEDROCK_ACCESS_ROLE: ${{ secrets.BEDROCK_ACCESS_ROLE }}
    with:
      skip_diff_reviewer_with_label_name: 'skip-diff-reviewer'
